---
title: "Using the IWRT Analysis Package in R"
author: "Joseph M. Burling"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Package Usage}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, echo=FALSE}
knitr::opts_chunk$set(eval=FALSE)
```

# Package Info

The `r.iwrt` package is used to handle the data exported from the MATLAB task IWRT, which is the main program in this GitHub repository. The IWRT task will export data in a root/main folder, typically called `data` and will look something like this:

- `data`
    - `SUB001`
        - `Infant_WRT_001_Name_calibration.csv`
        - `Infant_WRT_001_Name_data.csv`
        - `Infant_WRT_001_Name_info.txt`
        - `screenshots`
            - `Infant_WRT_001_Name_scrCap_001.csv`
            - `...`
        - `tracking`
            - `Infant_WRT_001_Name_eyeData_001.csv`
            - `...`
    - `SUB002`
    - `...`
    
The package will search through the main folder `data` for further processing.

# Usage

After installing the package (see GitHub `README.md` documentation) once, you must load the library each time you use it. After the library has been sucessfully loaded you can use the `iwrt_auto` function to automatically import and process the data within the main `data` folder. For help on using this function, and all documented R functions, preceed the function name with a question mark like so, `?iwrt_auto`. This will bring you to the function's documentation page.

The `iwrt_auto` function takes just one argument, the path to the main data folder. It will return an R list object containing several datasets. Take what you need, as you may not need datasets such as the complete set of data, but perhaps you may want to analyze ROI (Region of Interest) data. By default, regions of interest are the boundaries of the left and right images from the IWRT task data. After running `iwrt_auto` you can extract the `data.table` from the list called `roi` to get the ROI data. See code below as an example:


```r
# load the library
library(r.iwrt)

# make an object that holds the path to the main data folder
# change ../data to something else based on where your data is located
data_path <- "../data"

# use the auto function to return important datasets
iwrt_list <- iwrt_auto(data_path)

# extract complete, large dataset
full <- iwrt_list$complete

# extract ROI data only
roi <- iwrt_list$roi
```
    
At the moment, the two types of data you can extract automatically are `complete`, which is all the data merged and without ROI summaries, and `roi`, which is the data of ROI summary info for each participant.



# Package Options

The main function `iwrt_auto` relies on default options that have been set when the package is loaded. You may overwrite the default values of these options using the function `options()` and return an option value using `getOption()`

For example, to see and then overwrite how much to expand the ROI region, you can do the following:

```r
old_value <- getOption("roi.adj")
options(roi.adj=1.1)
```

You can also provide a list of options to overwrite:

```r
# quickly set new options and get old values at the same time
old_values <- options(list(tobii.filter.width=.67, tobii.filter.window=7))
```

Here is the complete list of options:

- `tobii.interpolation.window`: If any gaps in tracking data, this determines how wide the gap is allowed to be when attempting to fill the gap. This works for short durations where the person may blink or no data collected.

- `tobii.interpolation.method`: Whether to fill gaps linearlly or to use smoothing splines using (`spline(..., method="natural")`)

- `tobii.filter.width`: Width of the Gaussian distribution of the smoothing filter. Default to 99% of the distribution, lower values means a flatter distribution, approaching the mean of a series of values.

- `tobii.filter.window`: Window size of smoothing filter. Larger values returns smoother data but at a cost of introducing little variability. Defaults to a gaussian smoothing filter within a timespan of 92ms at 120hz.

- `tobii.coord.xrange`: Range corresponding to a particular tobii horizontal coordinate system. Defaults to the Active Display Coordinate System which is in the range of 0 to 1.

- `tobii.coord.yrange`: Range corresponding to a particular tobii vertical coordinate system. Defaults to the Active Display Coordinate System which is in the range of 0 to 1.

- `tobii.col.left.validity`: Name of validity column for the left eye

- `tobii.col.right.validity`: Name of validity column for the right eye

- `tobii.col.left.xaxis`: Name of tracking data column for left eye horizontal axis

- `tobii.col.right.xaxis`: Name of tracking data column for right eye horizontal axis

- `tobii.col.left.yaxis`: Name of tracking data column for left eye vertical axis 

- `tobii.col.right.yaxis`: Name of tracking data column for right eye vertical axis

- `roi.list`: list of ROI column names. Each sublist must have 4 character strings referring to column names corresponding to the left ROI coordinate, top ROI coordinate, right ROI coordinate, bottom ROI coordinate. All coordinates must be in this order (left, top, right, bottom), and the data for these columns must be in the same range as the `tobii.coord.xrange` and `tobii.coord.yrange` options. Currently this is a list with 2 sublists, each sublist is the names of columns corresponding to the coordinates of the left image and right image taken from the task data. 

- `roi.adj`: How much to increase or decrease the coordinates specified in the `roi.list` above. This is a multiplicative property. So if you set it to `1.1`, it will expand the box by 110%. 
       
        
# Advanced usage

If you wanted to process the data yourself you can use a series of functions to import the data on your own and do the processing on your own. To see a list of all available functions enter `?r.iwrt` into the R console. More functions to come.

```r
task_info <- import_task_data("path")
tracking_data <- import_tracking_data("path")
```

# Dataset info

## `complete` data column descriptions

This is both the task data (e.g., `Infant_WRT_001_Name_data.csv`) and tracking data (e.g., `Infant_WRT_001_Name_eyeData_001.csv`) merged together for all trials and all participants with some additional columns after further processing using the `iwrt_auto` function.

- `id`: id number entered in task subject info field.

- `name`: name as entered in subject info.

- `trial`: trial number of the task

- `file_task`: file name for the task related data

- `date`: date task was conducted

- `age`: age of participant as entered in subject info

- `imgStart`: onset of trial (microseconds)

- `audioStart`: onset of audio after brief fixation screen or attention getter (microseconds)

- `imgEnd`: offset of trial, due to end of trial time or looking away (microseconds)

- `tobiiOnset`: timestamp for when the tobii clock started

- `ptbOnset`: timestamp for when the Psychtoolbox clock started

- `new`: new or familiar images were used

- `left`: image type for left side of screen

- `right`: image type for right side of screen

- `word`: word said or tone

- `imgLx0`: starting point of left image for x axis, normalized

- `imgLy0`: starting point of left image for y axis, normalized

- `imgLx1`: ending point of left image for x axis, normalized

- `imgLy1`: ending point of left image for y axis, normalized

- `imgRx0`: starting point of right image for x axis, normalized

- `imgRy0`: starting point of right image for y axis, normalized

- `imgRx1`: ending point of right image for x axis, normalized

- `imgRy1`: ending point of right image for y axis, normalized

- `file_track`: file name for the eye tracking related data

- `tet_musec`: Tobii timestamp for tracking data points in microseconds

- `tet_musec_onset`: timestamp for when Tobii data buffer was written

- `ptb_musec_onset`: Psychtoolbox timestamp that matches up to Tobii data collection timestamp

- `left_eye_ucs_x`: left eye position in user coordinate system for x axis point (mm)

- `left_eye_ucs_y`: left eye position in user coordinate system for y axis point (mm)

- `left_eye_ucs_z`: left eye position in user coordinate system for z axis point (mm)

- `left_eye_tcs_x`: left eye position in trackbox coordinate system for x axis point (0,1)

- `left_eye_tcs_y`: left eye position in trackbox coordinate system for y axis point (0,1)

- `left_eye_tcs_z`: left eye position in trackbox coordinate system for z axis point (0,1)

- `left_gaze_acs_x`: left eye gaze point in active display coordinate system for x axis (0,1). **Used by default**

- `left_gaze_acs_y`: left eye gaze point in active display coordinate system for y axis (0,1). **Used by default**

- `left_gaze_ucs_x`: left eye gaze point for user coordinate system for x axis point (0,1)

- `left_gaze_ucs_y`: left eye gaze point for user coordinate system for y axis point (0,1)

- `left_gaze_ucs_z`: left eye gaze point for user coordinate system for z axis point (0,1)

- `left_pupil_diameter`: left eye pupil diameter (mm)

- `left_validity`: left eye validity code. lower the more valid from (0,1,2,3,4), See code matrix in SDK manual.

- `right_eye_ucs_x`: right eye position in user coordinate system for x axis point (mm)

- `right_eye_ucs_y`: right eye position in user coordinate system for y axis point (mm)

- `right_eye_ucs_z`: right eye position in user coordinate system for z axis point (mm)

- `right_eye_tcs_x`: right eye position in trackbox coordinate system for x axis point (0,1)

- `right_eye_tcs_y`: right eye position in trackbox coordinate system for y axis point (0,1)

- `right_eye_tcs_z`: right eye position in trackbox coordinate system for z axis point (0,1)

- `right_gaze_acs_x`: right eye gaze point in active display coordinate system for x axis (0,1). **Used by default**

- `right_gaze_acs_y`: right eye gaze point in active display coordinate system for y axis (0,1). **Used by default**

- `right_gaze_ucs_x`: right eye gaze point for user coordinate system for x axis point (0,1)

- `right_gaze_ucs_y`: right eye gaze point for user coordinate system for y axis point (0,1)

- `right_gaze_ucs_z`: right eye gaze point for user coordinate system for z axis point (0,1)

- `right_pupil_diameter`: right eye pupil diameter (mm)

- `right_validity`: right eye validity code. lower the more valid from (0,1,2,3,4), See code matrix in SDK manual.

- `por_x`: computed/processed eye position for x axis. used for ROI's

- `por_y`: computed/processed eye position for y axis. used for ROI's

- `t_elapsed`: time since beginning of trial (ms)

- `roi_left`: indicator of gaze point within left roi

- `roi_right`: indicator of gaze point within right roi

- `pre_audio_duration`: duration for when pre audio phase was shown

- `post_audio_duration`: duration for when post audio phase was shown 


## `roi` data columns descriptions

The new columns that have been added for the `roi` data correspond to how long the tracking coordinates are within some specified region of interest. The descriptions for each new column are the following:

- `phase_duration`: The length of a particular phase of the trial in milliseconds, which can be either pre audio phase or post audio phase.

- `time_segment`: Counter that increases when going from one ROI to the next. This is reset for each trial and for each phase of the trial. 

- `roi_dwell_time`: Amount of time in milliseconds for when the gaze was fixated within some specified region according to the `roi` column.

- `roi_onset`: Timestamp in milliseconds for when the first tracking point was obtained.

- `roi_offset`: Timestamp in milliseconds for when the last tracking point was obtained.

- `tracking_time`: Total amount of time in which tracking data was found regardless of whether or not it was within the ROI. May be less than the `phase_duration` if no data was able to be obtained for some amount of time, for example, if the participant was looking away.

- `trial_phase`: Variable indicating if the phase is before the onset of the audio/label or if the data corresponds to after the audio was administered.

- `roi`: Variable indicating which ROI the dwell time correponds to. Defaults to left and right image ROIs. If the ROI cannot be determined due to tracking `NA`'s then this field is `NA`. 

